spring:
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
    #url: jdbc:h2:mem:test
    url: jdbc:h2:file:./datasource/h2/jpa;AUTO_SERVER=TRUE
    username: root
    password: root
    initialization-mode: never
    platform: all
    name: 内存数据源
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true
logging:
  level:
    root: INFO
    com.application.mapper: DEBUG
server:
  servlet:
    session:
      timeout: 10s # session 会话连接超时日期,就是持续连接10s内如果没有连接成功则超时
      cookie:
        max-age: 10m # 这是session 真正的失效日期
        secure: false
        comment: beatiful
        http-only: true
#        path:
#        domain:
#        name: system    
jhipster:
  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"
    exposed-headers: "Authorization,Link,X-Total-Count"
    allow-credentials: true
    max-age: 1800
  async:
    core-pool-size: 2
    max-pool-size: 50
    queue-capacity: 10000
  security:
    remember-me:
      key: 4e431fe0f41cec2457ba464d1fa53d2e287a54e5e92c9dca30c68d95af40e1bbc2cc4d3d25f0f61049dc3934466e6586a8eb
    authentication:
      jwt:
        base64-secret: RFE2Y1NNTlRsRDNDLzJiblVQRnZMYUZ4WXVjV1huWWVYa1luY0NNT3hlTVU1QmI2ZVZ3N2pkVFBISjBHS08zSEV1NWNYMGVGSXh0S3ZTQURjSkdzWWJsRE5sTjg3cVpjdDUwSkxhQnR6WXlhOUdTNHc5YjBkazlmbnk1WXd4MFowT3hZYnZFUUU2dVVyWW1ET0IwbUtNeGNCbmlCc1dYOTFqSnhmNy9VTlc4JTNE
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000    
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      insert-strategy: default
      select-strategy: default
      update-strategy: default

application:
  secure:
    ignored:
      urls:
        - /login
        - /api/admin-login
